create table APP_USER
(
    ID                     BIGINT auto_increment primary key,
    GENDER                 CHARACTER VARYING(255),
    NAME_SET               CHARACTER VARYING(255),
    TITLE                  CHARACTER VARYING(255),
    GIVEN_NAME             CHARACTER VARYING(255),
    MIDDLE_INITIAL         CHARACTER VARYING(255),
    SURNAME                CHARACTER VARYING(255),
    STREET_ADDRESS         CHARACTER VARYING(255),
    CITY                   CHARACTER VARYING(255),
    STATE                  CHARACTER VARYING(255),
    STATE_FULL             CHARACTER VARYING(255),
    ZIP_CODE               CHARACTER VARYING(255),
    COUNTRY                CHARACTER VARYING(255),
    COUNTRY_FULL           CHARACTER VARYING(255),
    EMAIL_ADDRESS          CHARACTER VARYING(255),
    USER_NAME              CHARACTER VARYING(255),
    PASSWORD               CHARACTER VARYING(255),
    BROWSER_USER_AGENT     CHARACTER VARYING(255),
    TELEPHONE_NUMBER       CHARACTER VARYING(255),
    TELEPHONE_COUNTRY_CODE CHARACTER VARYING(255),
    MAIDEN_NAME            CHARACTER VARYING(255),
    BIRTHDAY               CHARACTER VARYING(255),
    AGE                    INTEGER,
    TROPICAL_ZODIAC        CHARACTER VARYING(255),
    CC_TYPE                CHARACTER VARYING(255),
    CC_NUMBER              CHARACTER VARYING(255),
    CVV2                   CHARACTER VARYING(255),
    CC_EXPIRES             CHARACTER VARYING(255),
    NATIONAL_ID            CHARACTER VARYING(255),
    UPS_TRACKING           CHARACTER VARYING(255),
    WESTERN_UNION_MTCN     CHARACTER VARYING(255),
    MONEYGRAM_MTCN         CHARACTER VARYING(255),
    COLOR                  CHARACTER VARYING(255),
    OCCUPATION             CHARACTER VARYING(255),
    COMPANY                CHARACTER VARYING(255),
    VEHICLE                CHARACTER VARYING(255),
    DOMAIN                 CHARACTER VARYING(255),
    BLOOD_TYPE             CHARACTER VARYING(255),
    POUNDS                 DOUBLE PRECISION,
    KILOGRAMS              DOUBLE PRECISION,
    FEET_INCHES            CHARACTER VARYING(255),
    CENTIMETERS            INTEGER,
    GUID                   CHARACTER VARYING(255),
    LATITUDE               DOUBLE PRECISION,
    LONGITUDE              DOUBLE PRECISION
);

create table ROLE
(
    ID   BIGINT auto_increment
        primary key,
    NAME CHARACTER VARYING(1000000000)
);

create table ROLE_USER
(
    ROLE_ID INTEGER not null
        references ROLE,
    USER_ID INTEGER not null
        references APP_USER,
    primary key (ROLE_ID, USER_ID)
);

create table TASK
(
    ID          INTEGER auto_increment primary key,
    NAME        CHARACTER VARYING(1000000000),
    DESCRIPTION CHARACTER VARYING(1000000000),
    TYPE        CHARACTER VARYING(1000000000),
    PARENT_ID   INTEGER,
    STATUS      CHARACTER VARYING(1000000000),
    START_DATE  CHARACTER VARYING(1000000000),
    END_DATE    CHARACTER VARYING(1000000000),
    SEQUENCE    INTEGER,
    ASSIGNED_TO INTEGER,
    constraint FOREIGN_KEY_NAME foreign key (ASSIGNED_TO) references APP_USER
);
